name: financial_wellness
description: "Financial Wellness is an app that helps people to keep track of their financial situation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  either_dart: ^1.0.0
  mocktail: ^1.0.4
  go_router: ^14.8.0
  get_it: ^8.0.3
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  flutter_masked_text2: ^0.9.1
  intl: ^0.19.0
  flutter_bloc: ^9.0.0
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.15
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  slang_build_runner: ^4.4.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
